# Copyright 2025 TigerGraph Inc.
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file or https://www.apache.org/licenses/LICENSE-2.0
#
# Permission is granted to use, copy, modify, and distribute this software
# under the License. The software is provided "AS IS", without warranty.

"""MCP tools for TigerGraph."""

from .connection_tools import (
    list_connections_tool,
    show_connection_tool,
    list_connections,
    show_connection,
)
from .schema_tools import (
    # Global schema operations (database level)
    get_global_schema_tool,
    get_global_schema,
    # Graph operations (database level)
    list_graphs_tool,
    create_graph_tool,
    drop_graph_tool,
    clear_graph_data_tool,
    list_graphs,
    create_graph,
    drop_graph,
    clear_graph_data,
    # Schema operations (graph level)
    get_graph_schema_tool,
    show_graph_details_tool,
    get_graph_schema,
    show_graph_details,
)
from .node_tools import (
    add_node_tool,
    add_nodes_tool,
    get_node_tool,
    get_nodes_tool,
    delete_node_tool,
    delete_nodes_tool,
    has_node_tool,
    get_node_edges_tool,
    add_node,
    add_nodes,
    get_node,
    get_nodes,
    delete_node,
    delete_nodes,
    has_node,
    get_node_edges,
)
from .edge_tools import (
    add_edge_tool,
    add_edges_tool,
    get_edge_tool,
    get_edges_tool,
    delete_edge_tool,
    delete_edges_tool,
    has_edge_tool,
    add_edge,
    add_edges,
    get_edge,
    get_edges,
    delete_edge,
    delete_edges,
    has_edge,
)
from .query_tools import (
    run_query_tool,
    run_installed_query_tool,
    install_query_tool,
    drop_query_tool,
    show_query_tool,
    get_query_metadata_tool,
    is_query_installed_tool,
    get_neighbors_tool,
    run_query,
    run_installed_query,
    install_query,
    drop_query,
    show_query,
    get_query_metadata,
    is_query_installed,
    get_neighbors,
)
from .data_tools import (
    create_loading_job_tool,
    run_loading_job_with_file_tool,
    run_loading_job_with_data_tool,
    get_loading_jobs_tool,
    get_loading_job_status_tool,
    drop_loading_job_tool,
    create_loading_job,
    run_loading_job_with_file,
    run_loading_job_with_data,
    get_loading_jobs,
    get_loading_job_status,
    drop_loading_job,
)
from .statistics_tools import (
    get_vertex_count_tool,
    get_edge_count_tool,
    get_node_degree_tool,
    get_vertex_count,
    get_edge_count,
    get_node_degree,
)
from .gsql_tools import (
    gsql_tool,
    gsql,
    generate_gsql_query_tool,
    generate_gsql,
    generate_cypher_query_tool,
    generate_cypher,
)
from .vector_tools import (
    # Vector schema tools
    add_vector_attribute_tool,
    drop_vector_attribute_tool,
    list_vector_attributes_tool,
    get_vector_index_status_tool,
    add_vector_attribute,
    drop_vector_attribute,
    list_vector_attributes,
    get_vector_index_status,
    # Vector data tools
    upsert_vectors_tool,
    load_vectors_from_csv_tool,
    load_vectors_from_json_tool,
    search_top_k_similarity_tool,
    fetch_vector_tool,
    upsert_vectors,
    load_vectors_from_csv,
    load_vectors_from_json,
    search_top_k_similarity,
    fetch_vector,
)
from .datasource_tools import (
    create_data_source_tool,
    update_data_source_tool,
    get_data_source_tool,
    drop_data_source_tool,
    get_all_data_sources_tool,
    drop_all_data_sources_tool,
    preview_sample_data_tool,
    create_data_source,
    update_data_source,
    get_data_source,
    drop_data_source,
    get_all_data_sources,
    drop_all_data_sources,
    preview_sample_data,
)
from .discovery_tools import (
    discover_tools_tool,
    get_workflow_tool,
    get_tool_info_tool,
    discover_tools,
    get_workflow,
    get_tool_info,
)
from .tool_registry import get_all_tools

__all__ = [
    # Connection profile operations
    "list_connections_tool",
    "show_connection_tool",
    "list_connections",
    "show_connection",
    # Global schema operations (database level)
    "get_global_schema_tool",
    "get_global_schema",
    # Graph operations (database level)
    "list_graphs_tool",
    "create_graph_tool",
    "drop_graph_tool",
    "clear_graph_data_tool",
    "list_graphs",
    "create_graph",
    "drop_graph",
    "clear_graph_data",
    # Schema operations (graph level)
    "get_graph_schema_tool",
    "show_graph_details_tool",
    "get_graph_schema",
    "show_graph_details",
    # Node tools
    "add_node_tool",
    "add_nodes_tool",
    "get_node_tool",
    "get_nodes_tool",
    "delete_node_tool",
    "delete_nodes_tool",
    "has_node_tool",
    "get_node_edges_tool",
    "add_node",
    "add_nodes",
    "get_node",
    "get_nodes",
    "delete_node",
    "delete_nodes",
    "has_node",
    "get_node_edges",
    # Edge tools
    "add_edge_tool",
    "add_edges_tool",
    "get_edge_tool",
    "get_edges_tool",
    "delete_edge_tool",
    "delete_edges_tool",
    "has_edge_tool",
    "add_edge",
    "add_edges",
    "get_edge",
    "get_edges",
    "delete_edge",
    "delete_edges",
    "has_edge",
    # Query tools
    "run_query_tool",
    "run_installed_query_tool",
    "install_query_tool",
    "drop_query_tool",
    "show_query_tool",
    "get_query_metadata_tool",
    "is_query_installed_tool",
    "get_neighbors_tool",
    "run_query",
    "run_installed_query",
    "install_query",
    "drop_query",
    "show_query",
    "get_query_metadata",
    "is_query_installed",
    "get_neighbors",
    # Loading job tools
    "create_loading_job_tool",
    "run_loading_job_with_file_tool",
    "run_loading_job_with_data_tool",
    "get_loading_jobs_tool",
    "get_loading_job_status_tool",
    "drop_loading_job_tool",
    "create_loading_job",
    "run_loading_job_with_file",
    "run_loading_job_with_data",
    "get_loading_jobs",
    "get_loading_job_status",
    "drop_loading_job",
    # Statistics tools
    "get_vertex_count_tool",
    "get_edge_count_tool",
    "get_node_degree_tool",
    "get_vertex_count",
    "get_edge_count",
    "get_node_degree",
    # GSQL tools
    "gsql_tool",
    "gsql",
    "generate_gsql_query_tool",
    "generate_gsql",
    "generate_cypher_query_tool",
    "generate_cypher",
    # Vector schema tools
    "add_vector_attribute_tool",
    "drop_vector_attribute_tool",
    "list_vector_attributes_tool",
    "get_vector_index_status_tool",
    "add_vector_attribute",
    "drop_vector_attribute",
    "list_vector_attributes",
    "get_vector_index_status",
    # Vector data tools
    "upsert_vectors_tool",
    "load_vectors_from_csv_tool",
    "load_vectors_from_json_tool",
    "search_top_k_similarity_tool",
    "fetch_vector_tool",
    "upsert_vectors",
    "load_vectors_from_csv",
    "load_vectors_from_json",
    "search_top_k_similarity",
    "fetch_vector",
    # Data Source tools
    "create_data_source_tool",
    "update_data_source_tool",
    "get_data_source_tool",
    "drop_data_source_tool",
    "get_all_data_sources_tool",
    "drop_all_data_sources_tool",
    "preview_sample_data_tool",
    "create_data_source",
    "update_data_source",
    "get_data_source",
    "drop_data_source",
    "get_all_data_sources",
    "drop_all_data_sources",
    "preview_sample_data",
    # Discovery tools
    "discover_tools_tool",
    "get_workflow_tool",
    "get_tool_info_tool",
    "discover_tools",
    "get_workflow",
    "get_tool_info",
    # Registry
    "get_all_tools",
]

